name: GrootAI
title: GrootAI | ML/DL group
description: GrootAI is a Machine Learning seminar group involving wide variety of people.
url: "https://grootai.github.io"
tags:
  - blog
  - machine learning
  - deep learning
  - ai
  - statistical learning
show_hero: true
paginate: 10
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: grootseminar@gmail.com
disqus_username: anonymous
