name: GrootAI
title: GrootAI | ML/DL group
description: GrootAI is Machine Learning Study Group composed of people from various fields. It started in March 2018.
url: "https://grootai.github.io"
tags:
  - blog
  - machine learning
  - deep learning
  - ai
  - statistical learning
show_hero: true
paginate: 10
menu:
  - title: Home
    url: /
  - title: Members
    url: /staff
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: grootseminar@gmail.com
disqus_username: anonymous
