name: GrootAI
title: GrootAI | A blog theme for Jekyll
description: GrootAI is a Machine Learning seminar group involving wide variety of people.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
disqus_username: disqus_username
